[project]
name = "doc-qa-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Claire-233", email = "741051856@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "openai>=3.6.0",
    "python-dotenv>=1.2.3",
    "tenacity>=9.1.4",
]

[project.scripts]
doc-qa-assistant = "doc_qa_assistant:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
